apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  selector:
    matchLabels:
      app: pythonapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - image: firatyasar/python-app:latest
        name: pythonapp
        env:
          # Use secret in real usage
        - name: MYSQL_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mysqlsecret
            key: mysql_password
        - name: MYSQL_USERNAME
          secretKeyRef:
            name: mysqlsecret
            key: mysql_username
        - name: MYSQL_DB
          secretKeyRef:
            name: mysqlsecret
            key: mysql_db
        - name: MYSQL_HOST
          secretKeyRef:
            name: mysqlsecret
            key: mysql_db
        - name: MYSQL_PORT
          secretKeyRef:
            name: mysqlsecret
            key: mysql_port
        ports:
        - containerPort: 3000
          name: pythonapp
---
apiVersion: v1
kind: Service
metadata:
  name: appsvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
  selector:
    app: pythonapp
  type: NodePort
